### ISSUE TITLE
What is correct installation setup for ALFWorld experiments?

### ISSUE THREAD

**Issue by stevenyangyj** [RL4VLM/RL4VLM#1]
Thank you very much for releasing the solid work!

I wonder how you conducted the ALFWorld experiments, as I found it seems so difficult to run this simulator in headless when I tried to reproduce the experimental results shown in your excellent paper based on a headless cloud server.

Looking forward to your answer!

**Comment by YX-S-Z** [comment]
Hi, thanks for checking our codes. We have provided the installation guide [here](https://github.com/RL4VLM/RL4VLM/tree/main/VLM_PPO_ALF#environment-setup), could you let us know what errors you are encountering during installation?
