### ISSUE TITLE
Experimental environment for deploying ALFWorld on a cluster

### ISSUE THREAD

**Issue by xiaxiaxiatengxi** [RL4VLM/RL4VLM#10]
I wanted to ask if we have an experimental environment for deploying ALFWorld on a cluster, or if our experimental server is a single Linux server. It seems quite challenging to deploy ALFWorld on a cluster...

**Comment by YX-S-Z** [comment]
Hi, thank you very much for the question -- we only install the ALFWorld on an ssh server instead of an experimental environment. In principle, it should be able to install in the computing environment, but since we do not have access to your environment, we cannot actually how to debug.

**Comment by xiaxiaxiatengxi** [comment]
Oh, thank for your replay. Installing ALFWorld on an SSH server is fine. But in a cluster environment, it have management  nodes and computing nodes. It’s more complex compared to an SSH server.

**Comment by YX-S-Z** [comment]
yes I understand, typically I would recommend first log in to the computing node from the management node, try to setup / debug the environment at the computing node.
