### ISSUE TITLE
Could you please provide the SFT models for each task?

### ISSUE THREAD

**Issue by DragonYang-code** [RL4VLM/RL4VLM#13]
My computing resources were not enough to complete the full parameter fine-tuning of the sft stage，Could you please provide the SFT models for each task?

**Comment by yuslzp** [comment]
Sure, which ones do you want, and how should I send it do you?

**Comment by DragonYang-code** [comment]
Cause I'm not able to run the full weight fine-tuning, I need the SFT models for all of the five tasks. Could you provide the download link of the weights through GoogleDrive, Dropbox or OneDrive. Or whatever is convenient for you.

**Comment by yuslzp** [comment]
Sure, I will provide the link when I have the link available. It should be done in a day or so.

**Comment by yuslzp** [comment]
Here are the link to the zip files of the 5 models https://huggingface.co/datasets/LEVI-Project/sft-model-data/tree/main. After downloading, you should do `zip -s0 sft.zip --out sft_new.zip` and unzip the `sft_new.zip`. The 5 models are inside. Please let me know if you have any other questions.

**Comment by DragonYang-code** [comment]
thanks for your sharing. It really helps me a lot.
