### ISSUE TITLE
How many num_updates

### ISSUE THREAD

**Issue by xiaxiaxiatengxi** [RL4VLM/RL4VLM#14]
In my script, the parameter args.num_processes is set to 1, but its default value is 16. What exactly does the parameter "args.num_processes" mean?

When using 8 Nvidia GPUs to train my agent, should I set num_processes to 8 or 1?

**Comment by YX-S-Z** [comment]
Thank you for your question, the `args.num_processes` means the number of processes per GPU. So in your case, you should set the num_rocesses to 1, but you will actually have 8 processes, since you are running 1 process on each GPU.

**Comment by xiaxiaxiatengxi** [comment]
> Thank you for your question, the `args.num_processes` means the number of processes per GPU. So in your case, you should set the num_rocesses to 1, but you will actually have 8 processes, since you are running 1 process on each GPU.

Thank you for your reply. When I used 8 GPUs to train the Webshop Agent, num_processes was set to 1. However, after [6/20] updates, the output actions were completely illegal. It seems that my settings are correct, and the problem might be with my reward settings.

**Comment by YX-S-Z** [comment]
Thank you for the followup. Could you elaborate more on the Webshop Agent, which task is this one? I think we do not have this environment.
