### ISSUE TITLE
SomeQuestion about image_obs

### ISSUE THREAD

**Issue by xiaxiaxiatengxi** [RL4VLM/RL4VLM#15]
How should we handle the setting for `image_obs` when we don't have image data? Should we set `image_obs` to `None` or use a zero tensor in PyTorch?

**Comment by YX-S-Z** [comment]
Hi, thank you for your question -- I am not sure what is the ultimate task you want to solve, but here are some general things I can you may consider:

1. If you still want to use the same VLM backbone model we currently use, I think setting `image_obs` to `None` will not cause additional runtime errors, but it is unclear whether this will help you with the final task.
2. Or if you are thinking of only text-based tasks, you can also consider using other text-based back-bone models (such as llama) as well.
