### ISSUE TITLE
Clarification on hardcoded tokens

### ISSUE THREAD

**Issue by anezuniga** [RL4VLM/RL4VLM#17]
I noticed that the tokens for the string '"action":' are hardcoded [here](https://github.com/RL4VLM/RL4VLM/blob/5fea947be561b2c05f9ded1bc2dfff69b7ac705f/VLM_PPO/a2c_ppo_acktr/llava_interface/interface.py#L66) as [29908, 2467, 1115].
However, when I decode these tokens using the tokenizer version [specified](https://github.com/RL4VLM/RL4VLM/blob/5fea947be561b2c05f9ded1bc2dfff69b7ac705f/LLaVA/pyproject.toml#L17) (tokenizers==0.15.1), they correspond to 'ợAndco'. Instead tokens [345, 1774, 1264] would correspond to '"action":'

Is there a specific reason for hardcoding these tokens? Could you also specify if any other tokenizer version is used in the project?

Thank you.

**Comment by YX-S-Z** [comment]
Thank you for the question, and we apologize for the sloppy implementation of the hard-coded `'"action":'`. The reason why we hard code these tokens is that we want to weight the sum log probabilities of the tokens after `'"action":'`. 

And you are right, I think the tokenizers got updated after installing [sentencepiece](https://github.com/google/sentencepiece). We are also unclear what is the best way to find the tokens that correspond to `'"action":'`. What we did previously was to decode every token and identify the tokens that can be decoded to `'"action":'`. 

One viable way is to directly check the encoded tokens of the text string `'"action":'`, but previously we did notice that the quotation mark `"` got encoded differently when it is at the start of the sentence. If you also want to hard code it, you may want to pay attention to this as well. 

But please do let us know if you found better way to deal with this hard coding method, we would be happy to update the code if we can find better ways to get the token ids.
