### ISSUE TITLE
how to solve this problem (after the input: alfworld-download 

### ISSUE THREAD

**Issue by pilipala00622** [RL4VLM/RL4VLM#18]
Traceback (most recent call last):
  File "/root/conda/envs/vrenv-alf/bin/alfworld-download", line 165, in <module>
    main()
  File "/root/conda/envs/vrenv-alf/bin/alfworld-download", line 121, in main
    zipped_filename = download(JSON_FILES_URL, dst=args.data_dir,
  File "/root/conda/envs/vrenv-alf/bin/alfworld-download", line 64, in download
    r.raise_for_status()  # Bad request.
  File "/root/conda/envs/vrenv-alf/lib/python3.10/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 416 Client Error: Range Not Satisfiable for url: https://objects.githubusercontent.com/github-production-release-asset-2e65be/303795676/85069e8f-5edf-42e3-8515-f18204489240?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240812%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240812T140548Z&X-Amz-Expires=300&X-Amz-Signature=a31300a018b74f4d96dca2f02281e24d36c486eac0678d5b160b4750e4ecb060&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=303795676&response-content-disposition=attachment%3B%20filename%3Djson_2.1.1_json.zip&response-content-type=application%2Foctet-stream

**Comment by yuslzp** [comment]
Could you try redownloading alfworld? I just retried `alfworld-download` on my end and it should end up like this
```
~$ alfworld-download
Downloading json_2.1.1_json.zip: 100%|███████████| 72.0M/72.0M [00:01<00:00, 46.4MB/s]
Extracting json_2.1.1_json.zip: 100%|█████████| 7302/7302 [00:00<00:00, 174248.61it/s]
7302 files skipped (use -f to overwrite).
Downloading json_2.1.1_pddl.zip: 100%|███████████| 34.9M/34.9M [00:01<00:00, 32.3MB/s]
Extracting json_2.1.1_pddl.zip: 100%|█████████| 7080/7080 [00:00<00:00, 145892.42it/s]
7080 files skipped (use -f to overwrite).
Downloading json_2.1.1_tw-pddl.zip: 100%|████████| 45.1M/45.1M [00:00<00:00, 45.2MB/s]
Extracting json_2.1.1_tw-pddl.zip: 100%|██████| 5234/5234 [00:00<00:00, 168882.12it/s]
5234 files skipped (use -f to overwrite).
```
Also, the error `416 Client Error: Range Not Satisfiable` typically occurs when a request is made for a specific range of bytes from a resource, but the server cannot fulfill that request. Also try to clear any cache/temporary files you download for alfworld and that might help. Please let me know if you get errors after you re-download.
