### ISSUE TITLE
Code question

### ISSUE THREAD

**Issue by Serega6678** [RL4VLM/RL4VLM#19]
Hello, thank you very much for your wonderful work @YX-S-Z !

I have a question about the COT splitting in RL. In particulaire, in the fragment where you split my the sequence of tokens, shouldn't there be `if match_index.shape[0] >= 1:` rather than `> 1`? From what I understood, your goal is to split it so that COT and the action would be on the different size of the match_index but this code would require the model to output this splitting sequence twice to make it work. Thanks!

Code link:
https://github.com/RL4VLM/RL4VLM/blob/main/VLM_PPO/a2c_ppo_acktr/llava_interface/interface.py#L70

**Comment by YX-S-Z** [comment]
Thank you very much for the question! [This](https://github.com/RL4VLM/RL4VLM/blob/main/VLM_PPO/a2c_ppo_acktr/llava_interface/interface.py#L70) is an inelegant fix for a runtime error. 

The TLDR: if we can find such a match, the return `match_index` should be a tensor whose first dimension should `> 1`, hence the first [if statement](https://github.com/RL4VLM/RL4VLM/blob/main/VLM_PPO/a2c_ppo_acktr/llava_interface/interface.py#L70) is to check whether we have found a pattern. 

If not the next line will try to find the last four tokens, and if the output does not have more than 4 tokens, we directly set the `sum_log_prob` to -2 [here](https://github.com/RL4VLM/RL4VLM/blob/main/VLM_PPO/a2c_ppo_acktr/llava_interface/interface.py#L76).

**Comment by Serega6678** [comment]
@YX-S-Z Thanks

My question was why do you do > 1? This means that discard the 1st occurrence occurrence of the pattern and choose the 2nd occurrence, right?

**Comment by YX-S-Z** [comment]
Oh I see, I think you are right, it should be `>=1` instead of `>1`. I just fixed the code. Thank you for spotting this.

**Comment by Serega6678** [comment]
Great, would be curious to see how it affects evaluation results
