### ISSUE TITLE
I have a question about your project. Why NLP backbone use mistral-7b?

### ISSUE THREAD

**Issue by xiaxiaxiatengxi** [RL4VLM/RL4VLM#2]
Hello, have we tried using llama2-7B or llama3-8B as the backbone of the language model?

**Comment by Jiayi-Pan** [comment]
Hey, at the time, the best 7b vlm is llava 1.6 mistral-7b, and we directly used it. We think llama should also work well

**Comment by YX-S-Z** [comment]
A little bit more on the development side -- when we started this project, we initially adopted the llava1.5 (which uses vicuna-7b), and we observed that the method works on llava1.5 as well (although we did not report such results in the paper). When llava1.6 was released, we directly switched to the 1.6 backbone and the initial version of llava1.6 uses mistral-7b as the LLM backbone.

**Comment by xiaxiaxiatengxi** [comment]
> A little bit more on the development side -- when we started this project, we initially adopted the llava1.5 (which uses vicuna-7b), and we observed that the method works on llava1.5 as well (although we did not report such results in the paper). When llava1.6 was released, we directly switched to the 1.6 backbone and the initial version of llava1.6 uses mistral-7b as the LLM backbone.



> A little bit more on the development side -- when we started this project, we initially adopted the llava1.5 (which uses vicuna-7b), and we observed that the method works on llava1.5 as well (although we did not report such results in the paper). When llava1.6 was released, we directly switched to the 1.6 backbone and the initial version of llava1.6 uses mistral-7b as the LLM backbone.

wa,cool! thank you for your repley.
I have been following your previous work, Archer. I recently came across your group's latest work. These are very meaningful piece of research.

**Comment by xiaxiaxiatengxi** [comment]
> Hey, at the time, the best 7b vlm is llava 1.6 mistral-7b, and we directly used it. We think llama should also work well

Hi, Are we planning to directly perform reinforcement learning (RL) training on the [llava-1.6-mistral-7b](https://huggingface.co/liuhaotian/llava-v1.6-mistral-7b) checkpoint?
