### ISSUE TITLE
Error occurs when fintune sft model in ALFworld

### ISSUE THREAD

**Issue by AlexWanghaoming** [RL4VLM/RL4VLM#27]
We met an error: 
`[2024-09-23 11:13:54,886] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 123969
[2024-09-23 11:13:54,887] [ERROR] [launch.py:321:sigkill_handler] `
with with return code = -11 when we fintuned sft model using [fintune.sh](https://github.com/RL4VLM/RL4VLM/blob/main/finetune.sh).
We modified [fintune.sh](https://github.com/RL4VLM/RL4VLM/blob/main/finetune.sh) script as:
`deepspeed --include localhost:0 \
    LLaVA/llava/train/train_mem.py \
    --deepspeed scripts/zero2.json \
    --model_name_or_path liuhaotian/llava-v1.6-mistral-7b \
    --version v1 \
    --data_path alf/alfworld.json \
    --image_folder alf_data_folder \
    --vision_tower openai/clip-vit-large-patch14-336 \
    --mm_projector_type mlp2x_gelu \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end False \
    --mm_use_im_patch_token False \
    --image_aspect_ratio pad \
    --group_by_modality_length True \
    --bf16 True \
    --output_dir /alpha/wanghaoming19/RL4VLM \
    --num_train_epochs 1 \
    --per_device_train_batch_size 16 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 1 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 50000 \
    --save_total_limit 1 \
    --learning_rate 2e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --dataloader_num_workers 4 \
    --lazy_preprocess True \
    # --report_to wandb`
could you please offer your json file for "--deepspeed" argument?

**Comment by YX-S-Z** [comment]
Hi could you check this one: https://github.com/RL4VLM/RL4VLM/blob/main/VLM_PPO/scripts/config_zero2.yaml ?

**Comment by AlexWanghaoming** [comment]
It seems that deepspeed accepts JSON format instead of YAML format. Do we need to perform the format conversion ourselves?
