### ISSUE TITLE
How to reproduce the paper results?

### ISSUE THREAD

**Issue by langfengQ** [RL4VLM/RL4VLM#28]
Hi authors.

I recently used your released [SFT models](https://huggingface.co/datasets/LEVI-Project/sft-model-data/tree/main) and then ran the Numberline tasks via script [run_nl.sh](https://github.com/RL4VLM/RL4VLM/blob/main/VLM_PPO/scripts/run_nl.sh) without modifying any hyperparameters. But I got the results as below. What's the possible reasons behind this? Could you provide guidance on how to get the paper results? Thank you.
![eed5b3086d20fed684bc6db54e11b25](https://github.com/user-attachments/assets/90ad17d2-fe68-45b3-8066-018383d447ac)

**Comment by YX-S-Z** [comment]
Hi thanks for you interest and your efforts. Please see our update on sept 13 [here](https://github.com/RL4VLM/RL4VLM?tab=readme-ov-file#release). We apologize for not making this codebase up-to-date.
