### ISSUE TITLE
Download "liuhaotian/llava-v1.6-mistral-7b"  get a error

### ISSUE THREAD

**Issue by xiaxiaxiatengxi** [RL4VLM/RL4VLM#3]
hi, When i use this code to download liuhaotian/llava-v1.6-mistral-7b model , but i get an error : 
"ValueError: The checkpoint you are trying to load has model type `llava_mistral` but Transformers does not recognize this architecture. This could be because of an issue with the checkpoint, or because your version of Transformers is out of date"
from transformers import AutoModelForCausalLM
model = AutoModelForCausalLM.from_pretrained("liuhaotian/llava-v1.6-mistral-7b")

So, could help me, how to use this model for our work!

**Comment by xiaxiaxiatengxi** [comment]
I download the model in the url https://huggingface.co/liuhaotian/llava-v1.6-mistral-7b/tree/main

I am loading the model now, so I don't guarantee it will work.

**Comment by YX-S-Z** [comment]
Thanks for checking with us -- we used the same checkpoint from huggingface, hence we believe this version should work.
