### ISSUE TITLE
Download ERROR

### ISSUE THREAD

**Issue by xiaxiaxiatengxi** [RL4VLM/RL4VLM#4]
conda activate vrenv
cd <path-to-this-repo>
pip install -e ../LLaVA
pip install -e ../gym-cards
pip install gymnasium[atari,accept-rom-license]
pip install stable-baselines3 wandb deepspeed sentencepiece git+https://github.com/openai/CLIP.git
pip install xformers

when i install the package follow these instructions. When i install xformers, i get this error.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
llava 1.2.2.post1 requires torch==2.1.2, but you have torch 2.3.0 which is incompatible.
torchvision 0.16.2 requires torch==2.1.2, but you have torch 2.3.0 which is incompatible.
Could you use pip list ,show me your package versions?

**Comment by xiaxiaxiatengxi** [comment]
Oh, i need pip install xformers==0.0.23.post1

**Comment by LeslieTrue** [comment]
My env should work.

accelerate                 0.21.0
aiofiles                   23.2.1
ale-py                     0.8.1
altair                     5.3.0
annotated-types            0.6.0
anyio                      4.3.0
asttokens                  2.4.1
attrs                      23.2.0
AutoROM                    0.4.2
AutoROM.accept-rom-license 0.6.1
bitsandbytes               0.43.1
certifi                    2024.2.2
charset-normalizer         3.3.2
click                      8.1.7
cloudpickle                3.0.0
comm                       0.2.2
contourpy                  1.2.1
cycler                     0.12.1
debugpy                    1.8.1
decorator                  5.1.1
deepspeed                  0.14.2
dnspython                  2.6.1
docker-pycreds             0.4.0
einops                     0.6.1
einops-exts                0.0.4
email_validator            2.1.1
exceptiongroup             1.2.1
executing                  2.0.1
Farama-Notifications       0.0.4
fastapi                    0.111.0
fastapi-cli                0.0.3
ffmpy                      0.3.2
filelock                   3.14.0
flash_attn                 2.5.8
fonttools                  4.51.0
fsspec                     2024.3.1
gitdb                      4.0.11
GitPython                  3.1.43
gradio                     4.16.0
gradio_client              0.8.1
gym-cards                  0.0.1        /root/test/RL4VLM-main/gym-cards
gymnasium                  0.29.1
h11                        0.14.0
hjson                      3.1.0
httpcore                   0.17.3
httptools                  0.6.1
httpx                      0.24.0
huggingface-hub            0.23.0
idna                       3.7
importlib_resources        6.4.0
ipykernel                  6.29.4
ipython                    8.24.0
jedi                       0.19.1
Jinja2                     3.1.4
joblib                     1.4.2
jsonschema                 4.22.0
jsonschema-specifications  2023.12.1
jupyter_client             8.6.1
jupyter_core               5.7.2
kiwisolver                 1.4.5
llava                      1.2.2.post1  /root/test/RL4VLM-main/LLaVA
markdown-it-py             3.0.0
markdown2                  2.4.13
MarkupSafe                 2.1.5
matplotlib                 3.8.4
matplotlib-inline          0.1.7
mdurl                      0.1.2
mpmath                     1.3.0
nest-asyncio               1.6.0
networkx                   3.3
ninja                      1.11.1.1
numpy                      1.26.4
nvidia-cublas-cu12         12.1.3.1
nvidia-cuda-cupti-cu12     12.1.105
nvidia-cuda-nvrtc-cu12     12.1.105
nvidia-cuda-runtime-cu12   12.1.105
nvidia-cudnn-cu12          8.9.2.26
nvidia-cufft-cu12          11.0.2.54
nvidia-curand-cu12         10.3.2.106
nvidia-cusolver-cu12       11.4.5.107
nvidia-cusparse-cu12       12.1.0.106
nvidia-nccl-cu12           2.20.5
nvidia-nvjitlink-cu12      12.4.127
nvidia-nvtx-cu12           12.1.105
orjson                     3.10.3
packaging                  24.0
pandas                     2.2.2
parso                      0.8.4
peft                       0.10.0
pexpect                    4.9.0
pillow                     10.3.0
pip                        24.0
platformdirs               4.2.1
prompt-toolkit             3.0.43
protobuf                   4.25.3
psutil                     5.9.8
ptyprocess                 0.7.0
pure-eval                  0.2.2
py-cpuinfo                 9.0.0
pydantic                   2.7.1
pydantic_core              2.18.2
pydub                      0.25.1
Pygments                   2.18.0
pynvml                     11.5.0
pyparsing                  3.1.2
python-dateutil            2.9.0.post0
python-dotenv              1.0.1
python-multipart           0.0.9
pytz                       2024.1
PyYAML                     6.0.1
pyzmq                      26.0.3
referencing                0.35.1
regex                      2024.5.10
requests                   2.31.0
rich                       13.7.1
rpds-py                    0.18.1
ruff                       0.4.4
safetensors                0.4.3
scikit-learn               1.2.2
scipy                      1.13.0
semantic-version           2.10.0
sentencepiece              0.1.99
sentry-sdk                 2.1.1
setproctitle               1.3.3
setuptools                 69.5.1
shellingham                1.5.4
Shimmy                     0.2.1
shortuuid                  1.0.13
six                        1.16.0
smmap                      5.0.1
sniffio                    1.3.1
stable_baselines3          2.3.2
stack-data                 0.6.3
starlette                  0.37.2
svgwrite                   1.4.3
sympy                      1.12
threadpoolctl              3.5.0
timm                       0.6.13
tokenizers                 0.15.1
tomlkit                    0.12.0
toolz                      0.12.1
torch                      2.3.0
torchvision                0.18.0
tornado                    6.4
tqdm                       4.66.4
traitlets                  5.14.3
transformers               4.37.2
triton                     2.3.0
typer                      0.12.3
typing_extensions          4.11.0
tzdata                     2024.1
ujson                      5.10.0
urllib3                    2.2.1
uvicorn                    0.29.0
uvloop                     0.19.0
wandb                      0.17.0
watchfiles                 0.21.0
wavedrom                   2.0.3.post3
wcwidth                    0.2.13
websockets                 11.0.3
wheel                      0.43.0
xformers                   0.0.26.post1

**Comment by xiaxiaxiatengxi** [comment]
> My env should work.
> 
> accelerate 0.21.0 aiofiles 23.2.1 ale-py 0.8.1 altair 5.3.0 annotated-types 0.6.0 anyio 4.3.0 asttokens 2.4.1 attrs 23.2.0 AutoROM 0.4.2 AutoROM.accept-rom-license 0.6.1 bitsandbytes 0.43.1 certifi 2024.2.2 charset-normalizer 3.3.2 click 8.1.7 cloudpickle 3.0.0 comm 0.2.2 contourpy 1.2.1 cycler 0.12.1 debugpy 1.8.1 decorator 5.1.1 deepspeed 0.14.2 dnspython 2.6.1 docker-pycreds 0.4.0 einops 0.6.1 einops-exts 0.0.4 email_validator 2.1.1 exceptiongroup 1.2.1 executing 2.0.1 Farama-Notifications 0.0.4 fastapi 0.111.0 fastapi-cli 0.0.3 ffmpy 0.3.2 filelock 3.14.0 flash_attn 2.5.8 fonttools 4.51.0 fsspec 2024.3.1 gitdb 4.0.11 GitPython 3.1.43 gradio 4.16.0 gradio_client 0.8.1 gym-cards 0.0.1 /root/test/RL4VLM-main/gym-cards gymnasium 0.29.1 h11 0.14.0 hjson 3.1.0 httpcore 0.17.3 httptools 0.6.1 httpx 0.24.0 huggingface-hub 0.23.0 idna 3.7 importlib_resources 6.4.0 ipykernel 6.29.4 ipython 8.24.0 jedi 0.19.1 Jinja2 3.1.4 joblib 1.4.2 jsonschema 4.22.0 jsonschema-specifications 2023.12.1 jupyter_client 8.6.1 jupyter_core 5.7.2 kiwisolver 1.4.5 llava 1.2.2.post1 /root/test/RL4VLM-main/LLaVA markdown-it-py 3.0.0 markdown2 2.4.13 MarkupSafe 2.1.5 matplotlib 3.8.4 matplotlib-inline 0.1.7 mdurl 0.1.2 mpmath 1.3.0 nest-asyncio 1.6.0 networkx 3.3 ninja 1.11.1.1 numpy 1.26.4 nvidia-cublas-cu12 12.1.3.1 nvidia-cuda-cupti-cu12 12.1.105 nvidia-cuda-nvrtc-cu12 12.1.105 nvidia-cuda-runtime-cu12 12.1.105 nvidia-cudnn-cu12 8.9.2.26 nvidia-cufft-cu12 11.0.2.54 nvidia-curand-cu12 10.3.2.106 nvidia-cusolver-cu12 11.4.5.107 nvidia-cusparse-cu12 12.1.0.106 nvidia-nccl-cu12 2.20.5 nvidia-nvjitlink-cu12 12.4.127 nvidia-nvtx-cu12 12.1.105 orjson 3.10.3 packaging 24.0 pandas 2.2.2 parso 0.8.4 peft 0.10.0 pexpect 4.9.0 pillow 10.3.0 pip 24.0 platformdirs 4.2.1 prompt-toolkit 3.0.43 protobuf 4.25.3 psutil 5.9.8 ptyprocess 0.7.0 pure-eval 0.2.2 py-cpuinfo 9.0.0 pydantic 2.7.1 pydantic_core 2.18.2 pydub 0.25.1 Pygments 2.18.0 pynvml 11.5.0 pyparsing 3.1.2 python-dateutil 2.9.0.post0 python-dotenv 1.0.1 python-multipart 0.0.9 pytz 2024.1 PyYAML 6.0.1 pyzmq 26.0.3 referencing 0.35.1 regex 2024.5.10 requests 2.31.0 rich 13.7.1 rpds-py 0.18.1 ruff 0.4.4 safetensors 0.4.3 scikit-learn 1.2.2 scipy 1.13.0 semantic-version 2.10.0 sentencepiece 0.1.99 sentry-sdk 2.1.1 setproctitle 1.3.3 setuptools 69.5.1 shellingham 1.5.4 Shimmy 0.2.1 shortuuid 1.0.13 six 1.16.0 smmap 5.0.1 sniffio 1.3.1 stable_baselines3 2.3.2 stack-data 0.6.3 starlette 0.37.2 svgwrite 1.4.3 sympy 1.12 threadpoolctl 3.5.0 timm 0.6.13 tokenizers 0.15.1 tomlkit 0.12.0 toolz 0.12.1 torch 2.3.0 torchvision 0.18.0 tornado 6.4 tqdm 4.66.4 traitlets 5.14.3 transformers 4.37.2 triton 2.3.0 typer 0.12.3 typing_extensions 4.11.0 tzdata 2024.1 ujson 5.10.0 urllib3 2.2.1 uvicorn 0.29.0 uvloop 0.19.0 wandb 0.17.0 watchfiles 0.21.0 wavedrom 2.0.3.post3 wcwidth 0.2.13 websockets 11.0.3 wheel 0.43.0 xformers 0.0.26.post1

when i load /llava-v1.6-mistral-7b/ in this line, i got an error.
LlavaMistralForCausalLM.from_pretrained(model_path, cache_dir=cache_dir)
size mismatch for model.vision_tower.vision_tower.vision_model
