### ISSUE TITLE
how to start a X server?

### ISSUE THREAD

**Issue by mk322** [RL4VLM/RL4VLM#6]
Really amazing work and clean code. However, I got this error when I run your code to reproduce the Alfworld experiment. 

AssertionError: Invalid DISPLAY :0 - cannot find X server with xdpyinfo

I think there should be a startx.py file to start the X server? Also, does this process need a sudo permission? I am running on a cluster where I don't have sudo permission. How should I run it? Thanks a lot!

**Comment by mk322** [comment]
Also, after I installed all the package in conda environment, I got some errors when running the following two commands.
alfworld-play-tw, alfworld-play-thor

  File "/home/mkang/miniconda3/envs/alfworld/bin/alfworld-play-tw", line 90, in <module>
    args.problem = os.path.dirname(random.choice(problems))
  File "/home/mkang/miniconda3/envs/alfworld/lib/python3.10/random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

my alfworld package version is 0.3.2.

Thanks!

**Comment by yuslzp** [comment]
Hi, for startx feel free to check out https://github.com/alfworld/alfworld?tab=readme-ov-file#docker-setup from alfworld's official github page. I am not sure with the details but feel free to try out that first without sudo, and if it does not work, please let us know or leave them a issue too. 

For your second issue, I am not sure about the issue yet, and it might be a package version error. I am investigating this and I will let you know once I have any updates. Meanwhile, feel free to let us know if you face any other issues.

**Comment by mk322** [comment]
Hi, thanks for your reply. I've tried the solutions in the link. However, it seems I have to use a sudo command to run the simulator on a Headless machine.

**Comment by yuslzp** [comment]
I see, thanks for your update. For your second error, it might be you did not download files correctly to the right path. Please follow the https://github.com/alfworld/alfworld?tab=readme-ov-file#docker-setup to setup (especially with the download files part)

**Comment by AlexWanghaoming** [comment]
Have you solved this issue?
