### ISSUE TITLE
/usr/bin/ld: cannot find -lcurand

### ISSUE THREAD

**Issue by DragonYang-code** [RL4VLM/RL4VLM#9]
(vrenv) lhn@4GPU-A100:~/DATACENTER1/yl/projects/RL4VLM/VLM_PPO/scripts$ bash run_nl.sh
[2024-06-14 10:08:43,334] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-dev package with apt
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
 [WARNING]  Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.3
 [WARNING]  using untested triton version (2.3.0), only 1.0.0 is known to be compatible
W0614 10:08:44.580512 140268942746432 torch/distributed/run.py:757] 
W0614 10:08:44.580512 140268942746432 torch/distributed/run.py:757] *****************************************
W0614 10:08:44.580512 140268942746432 torch/distributed/run.py:757] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W0614 10:08:44.580512 140268942746432 torch/distributed/run.py:757] *****************************************
[2024-06-14 10:08:48,149] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-06-14 10:08:48,149] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-dev package with apt
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
 [WARNING]  Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
 [WARNING]  async_io: please install the libaio-dev package with apt
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
 [WARNING]  Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.3
 [WARNING]  using untested triton version (2.3.0), only 1.0.0 is known to be compatible
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.3
 [WARNING]  using untested triton version (2.3.0), only 1.0.0 is known to be compatible
using xformers
using xformers
[2024-06-14 10:08:50,379] [INFO] [comm.py:637:init_distributed] cdb=None
[2024-06-14 10:08:50,591] [INFO] [comm.py:637:init_distributed] cdb=None
[2024-06-14 10:08:50,591] [INFO] [comm.py:668:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
../../models/llava-v1.6-mistral-7b
../../models/llava-v1.6-mistral-7b
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████| 4/4 [00:15<00:00,  3.89s/it]
Model max context length:1024
['v_proj', 'k_proj', 'down_proj', 'q_proj', 'out_proj', 'mm_projector.2', 'gate_proj', 'fc2', 'fc1', 'up_proj', 'o_proj', 'mm_projector.0']
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████| 4/4 [00:19<00:00,  4.86s/it]
Model max context length:1024
['up_proj', 'out_proj', 'o_proj', 'v_proj', 'fc2', 'mm_projector.2', 'down_proj', 'mm_projector.0', 'gate_proj', 'fc1', 'q_proj', 'k_proj']
A chat between a curious human and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the human's questions. USER: <image>
You are playing a game called number line. You will see a target number and a current number in the image. And your goal is to move the current number closer to the target by choosing either adding or subtracting one to the current number. Your response should be a valid json file in the following format: 
{
 "current number": "x", 
"target number": "x", 
"thoughts": "{first read out the current and target number, then think carefully about which action to choose}", 
"action": "-" or "+" 
} ASSISTANT:
Using /home/lhn/.cache/torch_extensions/py310_cu121 as PyTorch extensions root...
Emitting ninja build file /home/lhn/.cache/torch_extensions/py310_cu121/cpu_adam/build.ninja...
Building extension module cpu_adam...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/1] c++ cpu_adam.o cpu_adam_impl.o -shared -lcurand -L/home/lhn/anaconda3/envs/vrenv/lib/python3.10/site-packages/torch/lib -lc10 -ltorch_cpu -ltorch -ltorch_python -o cpu_adam.so
FAILED: cpu_adam.so 
c++ cpu_adam.o cpu_adam_impl.o -shared -lcurand -L/home/lhn/anaconda3/envs/vrenv/lib/python3.10/site-packages/torch/lib -lc10 -ltorch_cpu -ltorch -ltorch_python -o cpu_adam.so
**/usr/bin/ld: cannot find -lcurand**
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
[rank1]: Traceback (most recent call last):
[rank1]:   File "/home/lhn/anaconda3/envs/vrenv/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 2107, in _run_ninja_build
[rank1]:     subprocess.run(
[rank1]:   File "/home/lhn/anaconda3/envs/vrenv/lib/python3.10/subprocess.py", line 524, in run
[rank1]:     raise CalledProcessError(retcode, process.args,
[rank1]: subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

[rank1]: The above exception was the direct cause of the following exception:

[rank1]: Traceback (most recent call last):
[rank1]:   File "/mnt/ssd1/lhn/yl/projects/RL4VLM/VLM_PPO/scripts/../main.py", line 306, in <module>
[rank1]:     main()
[rank1]:   File "/mnt/ssd1/lhn/yl/projects/RL4VLM/VLM_PPO/scripts/../main.py", line 170, in main
[rank1]:     actor_critic, optimizer, lr_scheduler = accelerator.prepare(actor_critic, optimizer, lr_scheduler)
[rank1]:   File "/home/lhn/anaconda3/envs/vrenv/lib/python3.10/site-packages/accelerate/accelerator.py", line 1198, in prepare
[rank1]:     result = self._prepare_deepspeed(*args)
[rank1]:   File "/home/lhn/anaconda3/envs/vrenv/lib/python3.10/site-packages/accelerate/accelerator.py", line 1531, in _prepare_deepspeed
[rank1]:     optimizer = DeepSpeedCPUAdam(optimizer.param_groups, **defaults)
[rank1]:   File "/home/lhn/anaconda3/envs/vrenv/lib/python3.10/site-packages/deepspeed/ops/adam/cpu_adam.py", line 94, in __init__
[rank1]:     self.ds_opt_adam = CPUAdamBuilder().load()
[rank1]:   File "/home/lhn/anaconda3/envs/vrenv/lib/python3.10/site-packages/deepspeed/ops/op_builder/builder.py", line 508, in load
[rank1]:     return self.jit_load(verbose)
[rank1]:   File "/home/lhn/anaconda3/envs/vrenv/lib/python3.10/site-packages/deepspeed/ops/op_builder/builder.py", line 555, in jit_load
[rank1]:     op_module = load(name=self.name,
[rank1]:   File "/home/lhn/anaconda3/envs/vrenv/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1309, in load
[rank1]:     return _jit_compile(
[rank1]:   File "/home/lhn/anaconda3/envs/vrenv/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1719, in _jit_compile
[rank1]:     _write_ninja_file_and_build_library(
[rank1]:   File "/home/lhn/anaconda3/envs/vrenv/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1832, in _write_ninja_file_and_build_library
[rank1]:     _run_ninja_build(
[rank1]:   File "/home/lhn/anaconda3/envs/vrenv/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 2123, in _run_ninja_build
[rank1]:     raise RuntimeError(message) from e
[rank1]: RuntimeError: Error building extension 'cpu_adam'
Exception ignored in: <function DeepSpeedCPUAdam.__del__ at 0x7f1cf24b4ee0>
Traceback (most recent call last):
  File "/home/lhn/anaconda3/envs/vrenv/lib/python3.10/site-packages/deepspeed/ops/adam/cpu_adam.py", line 102, in __del__
AttributeError: 'DeepSpeedCPUAdam' object has no attribute 'ds_opt_adam'
W0614 10:09:54.650543 140268942746432 torch/distributed/elastic/multiprocessing/api.py:851] Sending process 266708 closing signal SIGTERM
E0614 10:09:55.166986 140268942746432 torch/distributed/elastic/multiprocessing/api.py:826] failed (exitcode: 1) local_rank: 1 (pid: 266709) of binary: /home/lhn/anaconda3/envs/vrenv/bin/python
Traceback (most recent call last):
  File "/home/lhn/anaconda3/envs/vrenv/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/lhn/anaconda3/envs/vrenv/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/home/lhn/anaconda3/envs/vrenv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 964, in launch_command
    deepspeed_launcher(args)
  File "/home/lhn/anaconda3/envs/vrenv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 687, in deepspeed_launcher
    distrib_run.run(args)
  File "/home/lhn/anaconda3/envs/vrenv/lib/python3.10/site-packages/torch/distributed/run.py", line 870, in run
    elastic_launch(
  File "/home/lhn/anaconda3/envs/vrenv/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/lhn/anaconda3/envs/vrenv/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 263, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
../main.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-06-14_10:09:54
  host      : 4GPU-A100
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 266709)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

I‘ve checked my CUDA environment variables and reinstalled CUDA, but the issue still persists. How can I resolve this problem?

**Comment by YX-S-Z** [comment]
Hi, thanks for asking this question. Unfortunately, we have not encountered a similar problem before, so I cannot give a concrete solution to this question, as it looks like something related to linux or other stuff. But I did search the question on chatGPT and hopefully this response from chatGPT can give you some debugging inspiration 

=== chatGPT answer below === 

The error message "cannot find -lcurand" typically indicates that the linker cannot find the CUDA Random Number Generation library (cuRAND). This library is used in CUDA applications to generate random numbers on the GPU. Here's how you can resolve this issue:

1. **Ensure CUDA is Installed**: First, make sure that CUDA is installed on your system. You can check this by running `nvcc --version` in the command line to see if the NVIDIA CUDA Compiler (nvcc) is available.

2. **Install cuRAND**: If CUDA is installed but you're still seeing the error, it's possible that the cuRAND library isn't installed. You can install it by ensuring that the CUDA Toolkit is fully installed. cuRAND is included in the standard CUDA Toolkit installation.

3. **Check Library Path**: The linker may not be able to find the library if it's not in the standard search paths. You can add the path to cuRAND to your linker's search paths. This path is typically something like `/usr/local/cuda/lib64` on Linux. You can add it by using the `-L` flag in your gcc/g++ command, like so:
   ```bash
   g++ -L/usr/local/cuda/lib64 -lcurand ...
   ```

4. **Environment Variables**: Ensure that the `LD_LIBRARY_PATH` environment variable includes the path to the CUDA libraries:
   ```bash
   export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH
   ```

5. **Check File Existence**: Verify that `libcurand.so` actually exists in the CUDA library directory (`/usr/local/cuda/lib64`). If the file isn't there, you might need to reinstall CUDA.

6. **Permissions**: Ensure that you have the necessary permissions to access the CUDA directories and files.

By following these steps, you should be able to resolve the "cannot find -lcurand" error. If the problem persists, rechecking the installation of CUDA and the specific components may be necessary.

**Comment by DragonYang-code** [comment]
I fixed this problem through adding the -lcurand path to the `torch\utils\cpp_extension.py` file in the _write_ninja_file fuction.
